# Generated by Django 3.1.3 on 2020-11-12 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_auto_20201112_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='favority_by',
            field=models.ManyToManyField(related_name='favorite_song', to=settings.AUTH_USER_MODEL),
        ),
    ]
