# Generated by Django 3.1.3 on 2020-11-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20201112_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='favority_by',
            new_name='favorite_by',
        ),
    ]
